fix(auth, android): linkWithCredential will not attempt to upgrade from anon user (matches iOS) (#5694)
Description
When doing "linkWithCredential" in Android and the users exists relogin with this new user instead of launch exception 
Error: [auth/credential-already-in-use] This credential is already associated with a different user account.

Related  PR #4487 and PR #4552